version: '3'
services:
  web:
    container_name: web
    # restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    
# run tests using "docker exec -it web npm run test"
# the code below only runs tests once during "docker_compose up" 
  # tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]
   